"""Normalize Session events into Turn / ToolCall records used by the miner."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import PurePosixPath, PureWindowsPath
from typing import Iterator

from .loader import Session


@dataclass
class ToolCall:
    name: str        # Bash / Read / Edit / Grep / Write / WebFetch / ...
    signature: str   # the canonical token used for n-gram matching


@dataclass
class Turn:
    session_id: str
    cwd: str | None
    prompt: str | None
    tool_calls: list[ToolCall] = field(default_factory=list)
    ts: str | None = None


_BASH_HEAD_RE = re.compile(r"^\s*([A-Za-z][\w\-./]*)")


def _file_ext(path_str: str) -> str:
    if not path_str:
        return ""
    try:
        # works for both win and posix-style strings
        p = PureWindowsPath(path_str) if "\\" in path_str else PurePosixPath(path_str)
        suffix = p.suffix.lower()
    except Exception:
        suffix = ""
    return suffix or ""


def _bash_head(command: str) -> str:
    if not command:
        return ""
    # strip leading shell prefixes
    cmd = command.strip()
    # drop env var assignments: FOO=bar BAZ=qux real_cmd ...
    cmd = re.sub(r"^(?:[A-Z_][A-Z0-9_]*=\S+\s+)+", "", cmd)
    # heredoc, pipes, semicolons -- keep only the first program
    first = re.split(r"[\s|;&<>]", cmd, maxsplit=1)[0]
    m = _BASH_HEAD_RE.match(first)
    return (m.group(1) if m else first).lower()


def _tool_signature(name: str, raw_input: dict) -> str:
    """Build a short canonical token capturing the *intent* of the tool call."""
    if name == "Bash":
        head = _bash_head(raw_input.get("command", "") or "")
        return f"Bash:{head}" if head else "Bash"
    if name in {"Read", "Edit", "Write", "NotebookEdit"}:
        ext = _file_ext(raw_input.get("file_path", "") or raw_input.get("notebook_path", "") or "")
        return f"{name}:{ext}" if ext else name
    if name == "Glob":
        return "Glob"
    if name == "Grep":
        return "Grep"
    if name in {"WebFetch", "WebSearch"}:
        return name
    if name == "Agent":
        sub = (raw_input.get("subagent_type") or "general").lower()
        return f"Agent:{sub}"
    return name


_NOISE_PREFIXES = (
    "[Request interrupted",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<system-reminder>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<bash-input>",
    # Context compaction markers injected by Claude Code itself when a session
    # continues past the context window. Not a real user prompt.
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running",
)

_GREETING_PREFIXES = (
    "hi", "hello", "hey", "你好", "嗨",
)

# Exploratory "what can you do?" probes. They are repeated across sessions but
# never represent a real workflow worth mining into a Skill.
_PROBE_PHRASES = (
    "你能帮我做什么",
    "你能做什么",
    "你能干什么",
    "你会做什么",
    "what can you do",
    "what can you help",
)


def _is_greeting(text: str) -> bool:
    head = text.lstrip("，,。.!！?？ \t").lower()
    for g in _GREETING_PREFIXES:
        if head.startswith(g):
            # only the first ~30 chars matter; if it's "hi" + a real question
            # we still flag it because greeting-led intros aren't workflows.
            return True
    return False


def _is_probe(text: str) -> bool:
    # Only fire when the probe phrase opens the prompt — a real task that
    # mentions "what can you do" mid-sentence must not be filtered.
    head = text.lstrip("，,。.!！?？ \t").lower()
    return any(head.startswith(p) for p in _PROBE_PHRASES)


def _extract_prompt_text(content) -> str | None:
    """user.message.content can be a string or a list of {type:'text', text:...}."""
    if isinstance(content, str):
        text = content.strip()
    elif isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                t = block.get("text", "")
                if isinstance(t, str):
                    parts.append(t)
        text = "\n".join(parts).strip()
    else:
        return None
    if not text:
        return None
    for pref in _NOISE_PREFIXES:
        if text.startswith(pref):
            return None
    if _is_greeting(text):
        return None
    if _is_probe(text):
        return None
    return text


def _extract_tool_calls(assistant_content) -> list[ToolCall]:
    if not isinstance(assistant_content, list):
        return []
    out: list[ToolCall] = []
    for block in assistant_content:
        if not isinstance(block, dict):
            continue
        if block.get("type") != "tool_use":
            continue
        name = block.get("name") or "Unknown"
        raw_input = block.get("input") or {}
        out.append(ToolCall(name=name, signature=_tool_signature(name, raw_input)))
    return out


def iter_turns(session: Session) -> Iterator[Turn]:
    """Walk events and emit one Turn per user prompt.

    A Turn aggregates: the user prompt + every assistant tool_use that follows
    until the next user prompt.
    """
    pending: Turn | None = None

    for ev in session.events:
        if ev.type == "user":
            # skip non-text user payloads (tool_result blocks etc.)
            content = ev.raw.get("message", {}).get("content")
            prompt = _extract_prompt_text(content)
            if prompt is None:
                # could be a tool_result -- attach to existing turn but don't yield yet
                continue
            if pending is not None:
                yield pending
            pending = Turn(
                session_id=ev.session_id or session.session_id,
                cwd=ev.cwd,
                prompt=prompt,
                ts=ev.timestamp,
            )
        elif ev.type == "assistant" and pending is not None:
            assistant_content = ev.raw.get("message", {}).get("content")
            pending.tool_calls.extend(_extract_tool_calls(assistant_content))

    if pending is not None:
        yield pending
