"""Tests for noise/probe filtering in extractor and scrubbing in store.

IP literals here are RFC 5737 documentation addresses (TEST-NET-1/2/3).
They are reserved by IANA for examples and are not routable on the public
internet. Do not replace them with real addresses.
"""
from skill_miner.extractor import _extract_prompt_text
from skill_miner.miner import Candidate, NGram, PromptCluster
from skill_miner.store import State, upsert_candidates


def test_extractor_drops_context_compaction_marker():
    text = (
        "This session is being continued from a previous conversation that "
        "ran out of context. The summary below covers ..."
    )
    assert _extract_prompt_text(text) is None


def test_extractor_drops_caveat_marker():
    text = "Caveat: The messages below were generated by the user while running ..."
    assert _extract_prompt_text(text) is None


def test_extractor_drops_what_can_you_do_probes():
    assert _extract_prompt_text("你能帮我做什么？") is None
    assert _extract_prompt_text("你能帮我做什么啊") is None
    assert _extract_prompt_text("你能做什么？你是我的助手吗？") is None
    assert _extract_prompt_text("what can you do for me") is None


def test_extractor_keeps_real_prompts_containing_those_words_later():
    # "what can you do" buried deep in a real prompt should NOT be filtered.
    long = "Refactor this module. Then tell me what can you do to improve it." + (" extra" * 10)
    assert _extract_prompt_text(long) is not None


def test_store_scrubs_example_prompts():
    cluster = PromptCluster(members=[0], centroid={}, top_terms=["ssh"], medoid_idx=0)
    cand = Candidate(
        cluster=cluster,
        ngram=NGram(tokens=("Bash:ssh", "Bash:scp"), count=3, sessions={"s1"}),
        evidence_count=3,
        sessions={"s1", "s2", "s3"},
        confidence=0.6,
        example_prompts=[
            "connect to 203.0.113.47 with password=hunter2",
            "ssh root@server 198.51.100.5",
        ],
    )
    state = State()
    drafts = [("ssh-connect", "connect to host", "---\nname: ssh-connect\n---\nbody")]
    stored = upsert_candidates(state, [cand], drafts)
    joined = " ".join(stored[0].example_prompts)
    assert "203.0.113.47" not in joined
    assert "198.51.100.5" not in joined
    assert "hunter2" not in joined


def test_save_state_rescrubs_legacy_entries(tmp_path):
    """A historical entry written before scrubbing must be cleaned on save."""
    from skill_miner.store import StoredCandidate, save_state, load_state
    state = State()
    state.candidates["legacy"] = StoredCandidate(
        id="legacy",
        name="legacy",
        description="see 203.0.113.47 and password=hunter2",
        status="ignored",
        evidence_count=3,
        sessions=["s1"],
        confidence=0.5,
        ngram="Bash:ssh",
        example_prompts=["host 203.0.113.47 token=abcd1234efgh5678"],
        skill_md="see 198.51.100.5",
        created_at="2026-01-01",
        updated_at="2026-01-01",
    )
    save_state(state, state_dir=tmp_path)
    raw = (tmp_path / "state.json").read_bytes()
    assert b"203.0.113.47" not in raw
    assert b"hunter2" not in raw
    assert b"198.51.100.5" not in raw
    assert b"abcd1234efgh5678" not in raw
